---
output: html_document
---
#ESTATÍSTICA DESCRITIVA
```{r, include=FALSE}
library("mime")
library("stringi")
library("magrittr") 
library("Rcpp")
library("evaluate")
library("digest")
library("formatR")
library("highr")
library("markdown")
library("stringr")
library("yaml")
library("bitops")
library("caTools")
library("htmltools")
library("knitr")
library("rmarkdown")
library("e1071")
library("fBasics")
library("DAAG")
library("MASS")
library("fdth")
library("dplyr")
library("moments")
library("qcc")
library("rafalib")
library("reshape2")
library("survey")
library("raster")
library("knitr")
```

##QUESTÃO ED3
Sejam X1 ~ N(150,30), X2 ~ N(200,20) e X3 ~ N(100,14) independentes. Seja X = X1 - X2 + X3 também com distribuição normal. 

a) Calcule P(47 $\leq X \leq$ 58).

###Resposta letra a)
```{r}
P.58 <- pnorm(58, mean = (150-200+100), sd = sqrt(30^2+20^2+14^2))
P.47 <- pnorm(47, mean = (150-200+100), sd = sqrt(30^2+20^2+14^2))
P.58 - P.47
```