---
output: html_document
---
#ESTATÍSTICA DESCRITIVA
```{r, include=FALSE}
library("mime")
library("stringi")
library("magrittr") 
library("Rcpp")
library("evaluate")
library("digest")
library("formatR")
library("highr")
library("markdown")
library("stringr")
library("yaml")
library("bitops")
library("caTools")
library("htmltools")
library("knitr")
library("rmarkdown")
library("e1071")
library("fBasics")
library("DAAG")
library("MASS")
library("fdth")
library("dplyr")
library("moments")
library("qcc")
library("rafalib")
library("reshape2")
library("survey")
library("raster")
library("knitr")
```

## QUESTÃO ED7
Uma determinada empresa química faz uso de água superficial e de poços no seu processo produtivo, o qual inclui a operação de três plantas (figura 1). Um indicador do consumo de água (ICA) foi construído considerando a relação entre captação total de água (ou consumo de água) e produção total. 

a) Analise criticamente qual a influência da variabilidade dos dados no indicador, considerando as figuras 2 (a) e (b).

###Resposta letra a)
O gráfico de dispersão entre "Captação Total" e "Produção Total" não aparenta correlação significativa entre as variáveis, pois a produção total tende a um valor constante idependente da variação da captação. O gráfico de dispersão "Captação Total versus "ICA" apresenta uma correlação linear indicando a significância da predição de ICA a partir da captação. Por outro lado, o gráfico de dispersão "Produção Total versus "ICA" apresenta uma concentração de diferentes valores de ICA para a mesma produção total.