---
output: html_document
---
#INFERÊNCIA
```{r, include=FALSE}
library("mime")
library("stringi")
library("magrittr") 
library("Rcpp")
library("evaluate")
library("digest")
library("formatR")
library("highr")
library("markdown")
library("stringr")
library("yaml")
library("bitops")
library("caTools")
library("htmltools")
library("knitr")
library("rmarkdown")
library("e1071")
library("fBasics")
library("DAAG")
library("MASS")
library("fdth")
library("dplyr")
library("moments")
library("qcc")
library("rafalib")
library("reshape2")
library("survey")
library("raster")
library("knitr")
```

##QUESTÃO I10
Deseja-se estimar o intervalo de confiança da proporção de um experimento. Considere que há um incremento de 20% do custo de coleta de dados a cada retorno a campo. 

a) Indique como a pesquisa deveria ser realizada em campo de forma a minimizar o uso dos recursos financeiros, garantindo um nível de confiança de 90%.

###Resposta letra a
```{r}

```
