---
output: html_document
---
#INFERÊNCIA
```{r, include=FALSE}
library("mime")
library("stringi")
library("magrittr") 
library("Rcpp")
library("evaluate")
library("digest")
library("formatR")
library("highr")
library("markdown")
library("stringr")
library("yaml")
library("bitops")
library("caTools")
library("htmltools")
library("knitr")
library("rmarkdown")
library("e1071")
library("fBasics")
library("DAAG")
library("MASS")
library("fdth")
library("dplyr")
library("moments")
library("qcc")
library("rafalib")
library("reshape2")
library("survey")
library("raster")
library("knitr")
```

##QUESTÃO I4
Dado que a expressão para o tamanho da amostra para a proporção $\pi$ é $n = Z^{2}(\pi)(1-\pi)/(p-\pi)^{2}$.

a) Escreva detalhadamente como maximizar n se o parâmetro $\pi$ é desconhecido? Lembre-se: $\pi$ é a proporção da população.

###Resposta letra a)
```{r}
print("A resolução está na execução da primeira derivada desta função, e então obtém-se o valor máximo desta função.")
```